export const COPY = {
  brand: {
    name: 'PaperPay',
    tagline: 'Lee ciencia. Paga una vez.',
  },
  nav: {
    editorial: 'Panel editorial',
    back: '← Volver',
  },
  home: {
    badge: 'Red Stellar · USDC · Acceso en ~5 segundos',
    heroHeadline: 'Lee ciencia por',
    heroPrice: '$0.50',
    heroSubtitle: 'Sin cuenta. Sin suscripción.',
    heroDescription:
      'Accede a artículos científicos con un solo clic. Paga únicamente lo que lees.',
    searchPlaceholder: 'Buscar por título, autores o palabras clave...',
    allDisciplines: 'Todos',
    priceOriginal: '$39.95 USD',
    pricePaper: '$0.50 USDC',
    priceOriginalNote: 'por artículo en editorial',
    pricePaperNote: 'por artículo en PaperPay',
    howItWorksTitle: 'Cómo funciona',
    howItWorksSubtitle: 'Sin cuenta, sin contraseñas, sin suscripciones',
    howItWorksSteps: [
      {
        number: '01',
        title: 'Encuentra tu artículo',
        description: 'Busca por título, autor o disciplina y lee el resumen gratis antes de pagar.',
      },
      {
        number: '02',
        title: 'Paga con tu wallet',
        description:
          'Conecta tu wallet Freighter y aprueba $0.50 USDC. La transacción tarda ~5 segundos en Stellar.',
      },
      {
        number: '03',
        title: 'Lee sin límites',
        description:
          'Acceso completo durante 24 horas. El 98% es para la editorial; PaperPay cobra 2%.',
      },
    ],
    papersTitle: 'Artículos destacados',
    papersSubtitle: 'Acceso inmediato · Sin suscripción',
    readFor: 'Leer por',
    purchased: 'Comprado',
    purchasedFilter: 'Comprados',
    readNow: 'Leer ahora',
    accessUntil: 'Acceso hasta',
    noResults: 'No se encontraron artículos para tu búsqueda.',
    loadError: 'No pudimos cargar el catálogo. Revisa tu conexión e intenta de nuevo.',
    retry: 'Reintentar',
    sortLabel: 'Ordenar',
    sortNewest: 'Más recientes',
    sortTitle: 'Título A-Z',
    sortDiscipline: 'Disciplina',
    clearFilters: 'Quitar filtros',
    emptyTitle: 'Sin resultados',
    trust: [
      { title: 'Sin cuenta', desc: 'Tu wallet es tu identidad: sin registro ni contraseñas.' },
      { title: 'Verificable on-chain', desc: 'Cada pago queda registrado y auditable en Stellar.' },
      { title: 'Liquidación en segundos', desc: 'Del pago a la lectura en unos 5 segundos.' },
    ],
    agents: {
      badge: 'Nuevo',
      title: 'Hecho también para agentes de IA',
      description:
        'Al construirse sobre HTTP 402, el mismo endpoint que usan las personas sirve a agentes autónomos: piden el artículo, reciben el 402, pagan y leen, sin intervención humana.',
      points: [
        'Mismo endpoint para humanos y para agentes',
        'Pago y acceso mediante el estándar abierto x402',
        'Ideal para pipelines de investigación automatizados',
      ],
    },
    footerLeft: '© 2026 PaperPay · Pagos en Stellar Testnet',
    footerRight: '98% a la editorial · 2% de comisión',
  },
  paper: {
    by: 'Por',
    publishedIn: 'Publicado en',
    doi: 'DOI',
    abstract: 'Resumen',
    references: 'Referencias',
    activeAccess: 'Acceso activo',
    previewEnds: 'Vista previa termina aquí',
    unlockToRead: 'Desbloquea el artículo completo para continuar leyendo.',
    notFound: 'No encontramos este artículo.',
    loadError: 'No pudimos cargar el artículo. Revisa tu conexión e intenta de nuevo.',
    retry: 'Reintentar',
    backHome: 'Volver al catálogo',
  },
  paywall: {
    locked: 'Artículo bloqueado',
    price: '$0.50 USDC',
    accessLabel: 'Acceso por 24 horas',
    ctaButton: 'Leer por $0.50 USDC',
    microcopy: 'Sin comisiones adicionales · Listo en ~5 segundos',
    priceBreakdown: '98% a la editorial · 2% a PaperPay',
    publisherPrice: '$39.95',
    publisherPriceNote: 'editorial',
    trust: ['98% para la editorial', 'Acceso por 24 horas', 'Verificable en blockchain'],
  },
  wallet: {
    modalTitle: 'Conecta tu wallet',
    modalSubtitle: 'Necesitas Freighter para pagar en Stellar.',
    trust: ['98% para la editorial', 'Sin intermediarios bancarios', 'Transacción verificable en blockchain'],
    connectButton: 'Conectar Freighter',
    wrongNetworkPath: 'Freighter → Configuración → Red → Testnet',
    close: 'Cerrar',
  },
  stepper: {
    guarantee: 'No se cobra nada más de $0.50',
    processing: 'Procesando',
    steps: {
      awaitingSignature: {
        label: 'Firma en tu wallet',
        description: 'Aprueba la transacción de $0.50 USDC en Freighter.',
      },
      settling: {
        label: 'Confirmando en Stellar',
        description: 'La red Stellar está procesando tu pago (~5 segundos).',
      },
      unlocked: {
        label: 'Desbloqueado',
        description: '¡Ya puedes leer el artículo completo!',
      },
    },
  },
  receipt: {
    title: 'Recibo de pago',
    confirmed: 'Acceso confirmado',
    amount: 'Monto',
    date: 'Fecha',
    validUntil: 'Válido hasta',
    txHash: 'Transacción',
    explorer: 'Ver en el explorador',
    demoNote: 'Pago simulado: esta transacción no existe en la red.',
    copied: '¡Copiado!',
    copy: 'Copiar',
    copyLabel: 'Copiar hash',
  },
  toast: {
    unlocked: '¡Listo! Ya puedes leer el artículo completo.',
    dismiss: 'Cerrar notificación',
  },
  errors: {
    NO_WALLET: {
      title: 'Wallet no detectada',
      description: 'Instala la extensión Freighter para continuar.',
      action: 'Instalar Freighter',
    },
    WRONG_NETWORK: {
      title: 'Red incorrecta',
      description: 'Tu wallet no está en Testnet. Cámbiala desde la configuración de Freighter.',
      action: 'Ya la cambié, reintentar',
    },
    INSUFFICIENT_FUNDS: {
      title: 'Fondos insuficientes',
      description: 'Necesitas al menos $0.50 USDC en tu wallet.',
      action: 'Obtener USDC de prueba',
    },
    NO_TRUSTLINE: {
      title: 'USDC no activado',
      description: 'Agrega USDC a tu wallet antes de continuar.',
      action: 'Activar USDC',
    },
    USER_REJECTED: {
      title: 'Pago cancelado',
      description: 'No se cobró nada. Puedes intentarlo de nuevo cuando quieras.',
      action: 'Intentar de nuevo',
    },
    EXPIRED: {
      title: 'Acceso expirado',
      description: 'Tu acceso de 24 horas ya venció. Paga de nuevo para seguir leyendo.',
      action: 'Pagar de nuevo',
    },
    PAYMENT_FAILED: {
      title: 'No se pudo completar el pago',
      description: 'Hubo un problema al procesar el pago. No se cobró nada.',
      action: 'Intentar de nuevo',
    },
  },
  dashboard: {
    title: 'Panel editorial',
    subtitle: 'Ingresos y estadísticas de tu publicación',
    liveBadge: 'En vivo · testnet',
    loadError: 'No pudimos leer los pagos en la red. Intenta de nuevo.',
    retry: 'Reintentar',
    txEmpty: 'Aún no hay lecturas pagadas. Compra un artículo para verlo aquí.',
    kpis: {
      reads: 'Lecturas totales',
      readsSub: 'últimos 30 días',
      earnings: 'Ingresos editorial',
      earningsSub: 'USDC · acumulado',
      fee: 'Comisión PaperPay (2%)',
      feeSub: 'USDC · 2% de comisión',
    },
    chartTitle: 'Lecturas en los últimos 14 días',
    readsUnit: 'lecturas',
    distributionTitle: 'Distribución por lectura',
    distributionPublisher: 'Editorial',
    distributionPlatform: 'PaperPay',
    txTitle: 'Transacciones recientes',
    txHeaders: {
      date: 'Fecha',
      amount: 'Monto',
      reader: 'Lector',
      tx: 'Transacción',
    },
  },
  debug: {
    title: 'Panel de depuración',
    forceState: 'Forzar estado:',
    forceError: 'Forzar error:',
  },
}
